server:
  port: 8082
spring:
  application:
    name: log-service
  config:
    import:
      - nacos:user.properties?group=DEFAULT_GROUP
  nacos:
    config:
      server-addr: 10.7.0.1:8848
  cloud:
    nacos:
      discovery:
        server-addr: 10.7.0.1:8848
      server-addr: 10.7.0.1:8848
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.7.0.1:3306/log?useSSL=false&serverTimezone=UTC
    username: root
    password: liajay@0807

rocketmq:
  name-server: localhost:9876
  logging:
    topic: USER_LOG_TOPIC